### ISSUE TITLE
Remove directories that won't be used from participant setup?

### ISSUE THREAD

**Issue by pab2163** [pab2163/REMIND#8]
It looks like we are not using the `ses-localizer`, `ses-real`, and `ses-sham` subdirectories within each participant folder? Should we remove them to avoid confusion?

https://github.com/pab2163/REMIND/blob/9f565869b9ec32bc34dd7315c71c1530d1f13e63/murfi-rt-PyProject/scripts/createxml.sh#L31

**Comment by cccbauer** [comment]
yes, for r61 we can comment it out, but for r33 we will need the sham!

**Comment by pab2163** [comment]
got it, thanks! it looks like no files are ever added to the `ses-localizer` and `ses-real` subdirectories either -- are these necessary? from the pilots so far, it looks like files are only written to the `img`, `mask`, and `rest` directories -- should we be seeing outputs show up elsewhere?

**Comment by cccbauer** [comment]
ok, so lets better delete them so it is cleaner
